### ISSUE TITLE
Use class `super` for async function

### ISSUE THREAD

**Issue by brad-decker** [jhen0409/babel-preset-es2015-node6#5] opened 2016-07-13 20:50 UTC
I'm sure this is just user error or not knowing what other piece I need to add to this to make this work, but this is what i'm getting when i try to use async/await with object super. 

.babelrc: 

``` json
{
  "presets": [
    "es2015-node6",
    "stage-1"
  ]
}
```

minimal code to reproduce:

``` js
class Master {
  async setup() {
    console.log('hi');
  }
}

class Child extends Master {
  async setupChild() {
    await super.setup();
  }
}

const x = new Child();

x.setupChild();
```

Compiled code:

``` js
'use strict';

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { return step("next", value); }, function (err) { return step("throw", err); }); } } return step("next"); }); }; }

let Master = class Master {
  setup() {
    return _asyncToGenerator(function* () {
      console.log('hi');
    })();
  }
};
let Child = class Child extends Master {
  setupChild() {
    return _asyncToGenerator(function* () {
      yield super.setup();
    })();
  }
};


const x = new Child();

x.setupChild();
```

error:

```
      yield super.setup();
            ^^^^^
SyntaxError: 'super' keyword unexpected here
```

**Comment by jhen0409** [comment] 2016-07-16 22:47
I send the issue to [Babel#T7495](https://phabricator.babeljs.io/T7495), it's a problem for use `super` for async function without `transform-es2015-classes`.

Updated: The issue is duplicate of [Babel#T6895](https://phabricator.babeljs.io/T6895).

**Comment by kirkouimet** [comment] 2016-09-24 05:00
+1

**Closed as completed** 2018-09-28 15:21 UTC
Labels: bug

**Comment by alex-tsx** [comment] 2024-04-17 02:48
+1
