### ISSUE TITLE
Doesn't work without transform-es2015-arrow-functions

### ISSUE THREAD

**Issue by perrin4869** [jhen0409/babel-preset-es2015-node6#3] opened 2016-04-27 08:23 UTC
The following, using `babel-preset-react` fails without `transform-es2015-arrow-functions`:

``` javascript
export default param => class extends Component {
  render() {
    return <MyComponent />;
  }
}
```

It doesn't compile the JSX.

**Comment by jhen0409** [comment] 2016-04-27 11:05
I cannot reproduce the problem, I get the correct compiled code:

``` js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = param => class extends Component {
  render() {
    return React.createElement(MyComponent, null);
  }
};
```

**Comment by perrin4869** [comment] 2016-04-27 13:19
Oh that's right! Didn't notice, it only fails if you add properties to the top:

``` javascript
export default param => class extends Component {
        static propTypes = {
                focusOnKeyDown: PropTypes.bool,
                onEnterKeyDown: PropTypes.func
        }

        render() {
                return <MyComponent />;
        }
}
```

My `.babelrc`:

```
{
  "presets": ["es2015-node6", "react"],
  "plugins": ["transform-object-rest-spread", "transform-class-properties"]
}
```

**Comment by perrin4869** [comment] 2016-04-27 13:26
To be clear, with the above `.babelrc`, the output is:

``` javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
        value: true
});

exports.default = param => {
        var _class, _temp;

        return class extends Component {

                render() {
                        return <MyComponent />;
                }
        };
};
```

Using:

```
{
  "presets": ["es2015-node6", "react"],
  "plugins": ["transform-object-rest-spread", "transform-class-properties", "transform-es2015-arrow-functions"]
}
```

You get:

``` javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
        value: true
});

exports.default = function (param) {
        var _class, _temp;

        return _temp = _class = class extends Component {

                render() {
                        return React.createElement(MyComponent, null);
                }
        }, _class.propTypes = {
                focusOnKeyDown: PropTypes.bool,
                onEnterKeyDown: PropTypes.func
        }, _temp;
};
```

**Comment by jhen0409** [comment] 2016-04-27 13:37
Got it. :)

It seems related to non-block arrow function, when I add `{return ...}` it works:

``` js
export default param => {
  return class App extends Component {
    static propTypes = {
      focusOnKeyDown: PropTypes.bool,
      onEnterKeyDown: PropTypes.func
    }

    render() {
      return <MyComponent />;
    }
  }
}
```

**Comment by jhen0409** [comment] 2016-04-27 14:14
I send a PR for `transform-class-properties`, please waiting. :)

**Comment by perrin4869** [comment] 2016-04-27 14:26
damn, super thanks!!!!! Looking forward for the PR landing!

**Comment by jhen0409** [comment] 2016-05-18 03:58
It's fixed by `babel-plugin-transform-class-properties@6.9.0`.

**Closed as completed by jhen0409** 2016-05-18 03:58 UTC
Labels: bug

**Comment by perrin4869** [comment] 2016-05-18 04:22
Awesome! Thanks!
